image: gradle:4.8.1

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - gradle build -p TourGuide

unit-test-job:
  stage: test
  script:
    - echo "test"

deploy:
  stage: deploy
  script:
    - echo "deploy"