image: gradle:4.8.1

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - gradle assemble -p TourGuide
  artifacts:
    paths:
    - build/executable-binary-file-v1

unit-test-job:
  stage: test
  script:
    - gradle check -p TourGuide

deploy:
  stage: deploy
  script:
    - echo "deploy"